title: Jason Sevilla
description: >-
  Cybersecurity Professor | Threat Hunter | AI Workflow Architect
url: "https://jasonsevilla.github.io"
github_username: jasonsevilla

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
